[phases.setup]
nixPkgs = ["nodejs_20", "npm-10_x"]

[phases.install]
dependsOn = ["setup"]
cmds = [
  "npm install --legacy-peer-deps",
  "cd frontend && npm install --legacy-peer-deps",
  "cd ../backend && npm install --legacy-peer-deps"
]

[phases.build]
dependsOn = ["install"]
cmds = [
  "cd frontend && npm run build",
  "cd ../backend && npm run build"
]

[start]
cmd = "cd backend && node dist/index.js"
